// <auto-generated />
using System;
using MTGTournamentDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTGTournamentDashboard.Migrations
{
    [DbContext(typeof(MetaDbContext))]
    [Migration("20260525080540_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MTGTournamentDashboard.Data.Entities.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Archetype")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchetypeRulesVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Draws")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinalRank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainboardJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SideboardJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Archetype");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId", "PlayerId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("MTGTournamentDashboard.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Handle")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Handle");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MTGTournamentDashboard.Data.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeckAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeckBId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerDeckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeckAId");

                    b.HasIndex("DeckBId");

                    b.HasIndex("WinnerDeckId");

                    b.HasIndex("TournamentId", "RoundNumber");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("MTGTournamentDashboard.Data.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeInWinrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Format", "Date");

                    b.HasIndex("Source", "SourceUrl")
                        .IsUnique();

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("MTGTournamentDashboard.Data.Entities.Deck", b =>
                {
                    b.HasOne("MTGTournamentDashboard.Data.Entities.Player", "Player")
                        .WithMany("Decks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTGTournamentDashboard.Data.Entities.Tournament", "Tournament")
                        .WithMany("Decks")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("MTGTournamentDashboard.Data.Entities.Round", b =>
                {
                    b.HasOne("MTGTournamentDashboard.Data.Entities.Deck", "DeckA")
                        .WithMany()
                        .HasForeignKey("DeckAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTGTournamentDashboard.Data.Entities.Deck", "DeckB")
                        .WithMany()
                        .HasForeignKey("DeckBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MTGTournamentDashboard.Data.Entities.Tournament", "Tournament")
                        .WithMany("Rounds")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGTournamentDashboard.Data.Entities.Deck", "WinnerDeck")
                        .WithMany()
                        .HasForeignKey("WinnerDeckId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeckA");

                    b.Navigation("DeckB");

                    b.Navigation("Tournament");

                    b.Navigation("WinnerDeck");
                });

            modelBuilder.Entity("MTGTournamentDashboard.Data.Entities.Player", b =>
                {
                    b.Navigation("Decks");
                });

            modelBuilder.Entity("MTGTournamentDashboard.Data.Entities.Tournament", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
